# Docker Compose para o Sistema de Gerenciamento de Alunos
version: '3.8'

services:
  # Backend ASP.NET Core
  gerenciador-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gerenciador-alunos-backend
    ports:
      - "5226:5226"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5226
      - ConnectionStrings__DefaultConnection=${DATABASE_URL}
    networks:
      - gerenciador-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5226/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  gerenciador-network:
    driver: bridge

# Para uso futuro - PostgreSQL local (opcional)
# Descomente se quiser usar PostgreSQL local em vez do Supabase
#
# volumes:
#   postgres_data:
#
# services:
#   postgres:
#     image: postgres:15-alpine
#     container_name: gerenciador-postgres
#     environment:
#       POSTGRES_DB: gerenciador_alunos
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - gerenciador-network
#     restart: unless-stopped
